### PR TITLE
RiseOS Dependencies

### PR DESCRIPTION
**Pull request by sgrove**

### CODE REVIEW

**Comment by yunxing** [comment]
Lots of new packages! Let me run the conversion locally first to make sure it doesn't create issues.

**Comment by sgrove** [comment]
Also, a lot of them need to come from the `mirage-dev` opam repo, not sure how to describe that. Hopefully nailing everything down declaratively will be simple in the future

**Comment by yunxing** [comment]
It won't be hard to add support for a second opam repo. But I'm not sure if we would publish a "dev" package to the official npm repo though.

**Comment by sgrove** [comment]
Any thoughts on supporting "head"/dev versions of packages and/or merging this PR?

**Comment by yunxing** [comment]
@sgrove Sorry just saw your last comment! I manually published most of your packages (see https://www.npmjs.com/package/@opam-alpha/mirage), but we've found an issue: we can't publish any packages that are 4.03 only, as the current npm / yarn constraint solver will inevitably install two versions of ocaml (https://github.com/yarnpkg/yarn/issues/579). Once that issue is fixed, we will be able to publish all packages so we can skip this PR/merge cycle. 

I don't think we would publish any packages to the npm registry that are dev version. However, for each opam repo, I can imagine we create a separate universe (org) on github, and convert packages as git repos like what we are doing here: https://github.com/npm-opam.

**Pull request closed without merging**
