### PR TITLE
Add reason-parser

### PR DESCRIPTION
**Pull request by tekknolagi**

### CODE REVIEW

**Comment by jordwalke** [comment]
I think we need 1.13.0 on npm:
https://www.npmjs.com/package/@opam-alpha/reason-parser
Current projects are failing because reason depends on 1.13 but it's not pushed to npm.

**Comment by jordwalke** [comment]
we need to shut this npm workflow down though and go to full opam or esy, so that we don't have to keep maintaining these syncs. Thanks for doing it in the mean time though, @tekknolagi

**Comment by tekknolagi** [comment]
@jordwalke how does 1.13.0 on npm happen? does it mirror opam pkg?

and let's just nuke npm stat please

**Comment by jordwalke** [comment]
Yeah, we can nuke npm stat. I'm just using opam either via opam directly or via esy anyways. Can you convert the `ReasonProject` to opam some time? That will enable us to nuke it.

I think it should be on `solvuu` btw. So it will require finding a way to make that work.

**Comment by tekknolagi** [comment]
I can convert ReasonProject to opam this afternoon with solvuu. Or at least I can start.

**Comment by tekknolagi** [comment]
solvuu-build has a lot of dependencies...

**Comment by jordwalke** [comment]
Good observation. I would not want to make it the default build for `ReasonProject`, unless that dependency was dropped. I filed an issue here - we'll see if solvuu is receptive.

https://github.com/solvuu/solvuu-build/issues/63

**Pull request merged**
